ViewComponent/ViewComponent/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ViewComponentExample.ViewComponents
{
    public class GridViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

ViewComponent/ViewComponent/Views/Home/About.cshtml
@{
	ViewBag.title = "About";
}

<h2>About</h2>
<p>lorem impshghfjvrkskcsfjemolxjefnighrjkc  jfwjkrewygh i</p>

ViewComponent/ViewComponent/Views/Home/Index.cshtml
@{
	ViewBag.title = "Home Page";
}

<h1>Welcome</h1>
<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
@await Component.InvokeAsync("Grid", new { Source = "Home" })

ViewComponent/ViewComponent/Views/Shared/Components/Grid/Default.cshtml
<div>
	<h3>Grid</h3>
	<table class="table w-100">
		<thead>
			<th>Sr.No</th>
			<th>Name</th>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>abc</td>
			</tr>
			<tr>
				<td>2</td>
				<td>bcd</td>
			</tr>
			<tr>
				<td>3</td>
				<td>cde</td>
			</tr>
		</tbody>
	</table>
</div>

ViewComponent/ViewComponent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @* @RenderBody() *@
        <div class="container">
            <div class="navbar">
                <div class="navbar-brand">
                    View Component app
                </div>
                <ul>
                    <li><a href="~/">Home</a></li>
                    <li><a href="~/about">About</a></li>
                </ul>
            </div>
            <div class="page-content">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>